import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "./model/Product.js";

dotenv.config({ path: ".env" });

const products = [
  {
    title: "AirFlex Runner Sneakers",
    brand: "Aurum",
    category: "Shoes",
    price: 2999,
    mrp: 4499,
    rating: 4.6,
    reviews: 1382,
    badge: "Best seller",
    image: "https://www.campusshoes.com/cdn/shop/files/LEVEL_LEVEL_WHT-L.GRY_07_831c7a2c-ff1b-4011-9268-b11f984219c6.webp?v=1757580207"
  },
  {
    title: "NoiseCancel Wireless Headphones",
    brand: "Sonic",
    category: "Electronics",
    price: 6499,
    mrp: 8999,
    rating: 4.4,
    reviews: 824,
    badge: "Deal",
    image: "https://www.boat-lifestyle.com/cdn/shop/files/Artboard_2_47c2719f-e0f0-4cba-97dd-39821af9454a_1800x.png?v=1752729573"
  },
  {
    title: "Everyday Oversized Hoodie",
    brand: "Northline",
    category: "Fashion",
    price: 1599,
    mrp: 2299,
    rating: 4.5,
    reviews: 512,
    badge: "Trending",
    image: "https://image.hm.com/assets/hm/cb/83/cb83dc14110d0dcf79088d373dd74d8dcb1eb0d7_xxl-1.jpg"
  },
  {
    title: "Classic Leather Wallet",
    brand: "Canto",
    category: "Accessories",
    price: 899,
    mrp: 1299,
    rating: 4.3,
    reviews: 291,
    badge: "Premium",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBEvqlW9QWsZ2DCx_fcIVwJ1ThQK5eVTMtOQ&s"
  },
  {
    title: "Minimal Analog Watch (Steel)",
    brand: "TimeArc",
    category: "Accessories",
    price: 3799,
    mrp: 5299,
    rating: 4.7,
    reviews: 944,
    badge: "Top rated",
    image: "https://orsga.in/cdn/shop/files/9237BlackGold-4_600x.jpg?v=1718876298"
  },
  {
    title: "Smart LED Desk Lamp",
    brand: "Glow",
    category: "Home",
    price: 1399,
    mrp: 1999,
    rating: 4.2,
    reviews: 218,
    badge: "New",
    image: "https://chronoslights.com/cdn/shop/files/Untitleddesign_1.png?v=1711706269&width=1080"
  },
  {
    title: "Cotton Relaxed Fit T-Shirt",
    brand: "Basics",
    category: "Fashion",
    price: 549,
    mrp: 799,
    rating: 4.1,
    reviews: 1770,
    badge: "Value",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcHb9gF_OV_aNrLEyBd6-7DD56t-_yfVzIbg&s"
  },
  {
    title: "TrailGrip Outdoor Sandals",
    brand: "Aurum",
    category: "Shoes",
    price: 1799,
    mrp: 2499,
    rating: 4.4,
    reviews: 363,
    badge: "Limited",
    image: "https://inc5shop.com/cdn/shop/files/INC-900321_Peach_1_045a5e3e-c00f-419d-890d-ca5f54949c52.jpg?v=1755491705"
  },
  {
    title: "Loose Fit Hoodie",
    brand: "H&M",
    category: "Fashion",
    price: 1499,
    mrp: 2299,
    rating: 4.6,
    reviews: 19000,
    badge: "Trending",
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSVnLE-bhItMvIwWvp-tFFeYQrsP8A9YI7OH8r9tIZUSMFyvDZc1a6BnD5nXkuAi68hggsTfpVkWa83x1_J81yG1lRzpBUwTu2ZFNozlpxivoFukClSZrk_6YAZHEx8VRnkJg&usqp=CAc"
  },
  {
    title: "Oversized Printed Hoodie",
    brand: "WhatTheFlex",
    category: "Fashion",
    price: 1999,
    mrp: 2799,
    rating: 4.5,
    reviews: 850,
    badge: "Best seller",
    image: "https://nobero.com/cdn/shop/files/222C021C-8EFF-4A86-A782-A25876663738.jpg?v=1732879745"
  },
  {
    title: "Softride Pro Running Shoes",
    brand: "Puma",
    category: "Shoes",
    price: 4199,
    mrp: 6999,
    rating: 4.2,
    reviews: 63,
    badge: "Premium",
    image: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/shoe/g/d/e/-original-imah64w2hgbx4ntr.jpeg?q=70"
  },
  {
    title: "Jogflow Running Shoes",
    brand: "Decathlon",
    category: "Shoes",
    price: 1599,
    mrp: 2499,
    rating: 4.6,
    reviews: 3600,
    badge: "Top rated",
    image: "https://images-static.nykaa.com/media/catalog/product/6/a/6a65bfbOPPUMAX00420519_0.jpg?tr=w-500"
  },
  {
    title: "Noise Twist Go Smartwatch",
    brand: "Noise",
    category: "Electronics",
    price: 1399,
    mrp: 2499,
    rating: 4.6,
    reviews: 214,
    badge: "Hot",
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQnSvrPdxNcwti-Mwvdh3BmbHTr3BxHJvPaBR-lYrT4HrlyFUQ7bMmyIrJMPQwTbx2oX_x6jF_Ug9oXz6neIXjoftmOH9GWQi83uMYhJh0p-46KPqj06744ZGxwZtePPBoDeg&usqp=CAc"
  },
  {
    title: "Apple Watch SE 3",
    brand: "Apple",
    category: "Electronics",
    price: 22999,
    mrp: 29999,
    rating: 4.8,
    reviews: 6100,
    badge: "Premium",
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQwGaYAkD1_6_FySfoIjQSOm-lDOHR1Do9AziY5uIDXr89NpMoL4gBBrSMxDYCh8lA_9Nxs0sM-icC8r4hXm4NSZesKo1lgh71w_sEDpvsEY-7EO1iTvusbjlk7dYfU7LkuWdyq9TI&usqp=CAc"
  },
  {
    title: "Boat Lunar Discovery Pro",
    brand: "Boat",
    category: "Electronics",
    price: 1299,
    mrp: 2999,
    rating: 4.4,
    reviews: 540,
    badge: "Value",
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQGkzERBkV17RJPhRofTKy1GOEpwEv7wNBwJSNA3XsmvGLtKIiiVwSuk-NmrOE2m5Oi4PzME1MjbPzJ5TQ6OfBJPXdozvINQpOtNHDG_FIlZPllb5IHw2gW0P2Vsvhs9QNPPE6XZSM&usqp=CAc"
  },
  {
    title: "Urban Cargo Joggers",
    brand: "Roadster",
    category: "Fashion",
    price: 1799,
    mrp: 2599,
    rating: 4.2,
    reviews: 1320,
    badge: "Trending",
    image: "https://cdn.fynd.com/v2/falling-surf-7c8bb8/fyprod/wrkr/products/pictures/item/free/original/superdry/M7010994A9ZO/0/WXxXZImItZ-410393558005_1.jpg"
  },
  {
    title: "Wireless Gaming Headset",
    brand: "boAt",
    category: "Electronics",
    price: 2499,
    mrp: 3999,
    rating: 4.5,
    reviews: 2180,
    badge: "Best seller",
    image: "https://www.tpstech.in/cdn/shop/products/01_8d54b9b4-cd26-4e71-98f6-4f11e6ea2e04.jpg?v=1613552011"
  },
  {
    title: "Wireless Bluetooth Headphones",
    brand: "SoundMax",
    category: "Electronics",
    price: 2999,
    mrp: 4999,
    rating: 4.6,
    reviews: 842,
    badge: "New",
    image: "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg",
  },
  {
    title: "Modern Table Lamp",
    brand: "GlowNest",
    category: "Home",
    price: 1499,
    mrp: 2299,
    rating: 4.4,
    reviews: 213,
    badge: "New",
    image: "https://images.pexels.com/photos/112811/pexels-photo-112811.jpeg",
  },
  {
    title: "Men Oversized Hoodie",
    brand: "UrbanFlex",
    category: "Fashion",
    price: 1799,
    mrp: 2699,
    rating: 4.5,
    reviews: 365,
    badge: "New",
    image: "https://images.pexels.com/photos/6311392/pexels-photo-6311392.jpeg",
  },
  {
    title: "Leather Office Backpack",
    brand: "CarryPro",
    category: "Accessories",
    price: 2499,
    mrp: 3799,
    rating: 4.7,
    reviews: 401,
    badge: "New",
    image: "https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg",
  },
  {
    title: "Smart Fitness Watch",
    brand: "FitPulse",
    category: "Electronics",
    price: 3999,
    mrp: 5999,
    rating: 4.5,
    reviews: 678,
    badge: "New",
    image: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg",
  },
  {
    title: "Decorative Flower Vase",
    brand: "HomeAura",
    category: "Home",
    price: 899,
    mrp: 1499,
    rating: 4.3,
    reviews: 146,
    badge: "New",
    image: "https://images.pexels.com/photos/4207790/pexels-photo-4207790.jpeg",
  },
  {
    title: "Wireless Gaming Mouse",
    brand: "GameCore",
    category: "Gaming",
    price: 1599,
    mrp: 2499,
    rating: 4.6,
    reviews: 312,
    badge: "New",
    image: "https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg",
  },
  {
    title: "Women Casual Sneakers",
    brand: "SprintX",
    category: "Footwear",
    price: 2799,
    mrp: 3999,
    rating: 4.7,
    reviews: 588,
    badge: "New",
    image: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
  },
  {
    title: "Portable Bluetooth Speaker",
    brand: "BassBeat",
    category: "Electronics",
    price: 1899,
    mrp: 2999,
    rating: 4.4,
    reviews: 255,
    badge: "New",
    image: "https://images.pexels.com/photos/63703/pexels-photo-63703.jpeg",
  },
  {
    title: "Minimal Wall Clock",
    brand: "TimeDecor",
    category: "Home",
    price: 1299,
    mrp: 1899,
    rating: 4.2,
    reviews: 129,
    badge: "New",
    image: "https://images.pexels.com/photos/2762247/pexels-photo-2762247.jpeg",
  },
  {
    title: "Women Denim Jacket",
    brand: "BlueEra",
    category: "Fashion",
    price: 2499,
    mrp: 3699,
    rating: 4.5,
    reviews: 298,
    badge: "New",
    image: "https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg",
  },
  {
    title: "Luxury Sunglasses",
    brand: "ShadeStyle",
    category: "Accessories",
    price: 999,
    mrp: 1699,
    rating: 4.3,
    reviews: 184,
    badge: "New",
    image: "https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg",
  },
  {
    title: "Mechanical Gaming Keyboard",
    brand: "KeyNova",
    category: "Gaming",
    price: 3499,
    mrp: 4999,
    rating: 4.8,
    reviews: 742,
    badge: "New",
    image: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg",
  },
  {
    title: "Ceramic Coffee Mug",
    brand: "CafeHome",
    category: "Kitchen",
    price: 499,
    mrp: 899,
    rating: 4.1,
    reviews: 117,
    badge: "New",
    image: "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg",
  },
  {
    title: "USB-C Fast Charger",
    brand: "Voltix",
    category: "Electronics",
    price: 799,
    mrp: 1299,
    rating: 4.4,
    reviews: 376,
    badge: "New",
    image: "https://images.pexels.com/photos/4526407/pexels-photo-4526407.jpeg",
  },
  {
    title: "Wooden Study Desk",
    brand: "OakSpace",
    category: "Furniture",
    price: 7499,
    mrp: 9999,
    rating: 4.5,
    reviews: 143,
    badge: "New",
    image: "https://images.pexels.com/photos/245240/pexels-photo-245240.jpeg",
  },
  {
    title: "Travel Duffel Bag",
    brand: "PackGo",
    category: "Travel",
    price: 2299,
    mrp: 3499,
    rating: 4.6,
    reviews: 291,
    badge: "New",
    image: "https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg",
  },
  {
    title: "Cotton Printed T-Shirt",
    brand: "TrendWear",
    category: "Fashion",
    price: 899,
    mrp: 1499,
    rating: 4.2,
    reviews: 226,
    badge: "New",
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSSX5yehdAREoxFaZTAz_48iQZosUfPSK9N64D71tLtHshWNCs0JSAhNky6izTvAMABsdIDzvyl7e1LWwGAZX5LFzkxC0oHcPkd__Vuuc5lI6Xqgbg&usqp=CAc",
  },
  {
    title: "Kitchen Knife Set",
    brand: "ChefMaster",
    category: "Kitchen",
    price: 1999,
    mrp: 2899,
    rating: 4.5,
    reviews: 164,
    badge: "New",
    image: "https://images.pexels.com/photos/4226806/pexels-photo-4226806.jpeg",
  },
  {
    title: "Adjustable Mobile Stand",
    brand: "Holdix",
    category: "Accessories",
    price: 399,
    mrp: 699,
    rating: 4.0,
    reviews: 92,
    badge: "New",
    image: "https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg",
  },
];

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    await Product.deleteMany(); // Clear existing products
    console.log("Cleared existing products");

    await Product.insertMany(products);
    console.log("Products seeded successfully");

    mongoose.connection.close();
  } catch (error) {
    console.error("Error seeding products:", error);
    mongoose.connection.close();
  }
};

seedProducts();